CREATE TABLE Posts(
    id SERIAL PRIMARY KEY ,
    user_id INTEGER NOT NULL ,
    title VARCHAR(255) NOT NULL ,
    content TEXT NOT NULL ,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id)
);