CREATE TABLE Comments(
    id SERIAL PRIMARY KEY ,
    post_id INTEGER NOT NULL ,
    user_id INTEGER NOT NULL ,
    comment_text TEXT NOT NULL ,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES Posts(id),
    FOREIGN KEY (user_id) REFERENCES Users(id)
);